# Generated by Django 5.2.1 on 2025-05-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_user_bio_user_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
