# Generated by Django 5.2.1 on 2025-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_rename_date_of_birth_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Баланс'),
        ),
    ]
