# Generated by Django 5.2.1 on 2025-06-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_alter_user_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
