# Generated by Django 5.2.1 on 2025-06-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Дата и время, до которого пари действует', null=True, verbose_name='Срок пари'),
        ),
    ]
