# Generated by Django 5.2.1 on 2025-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_bet_arbiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=1, default=1000, max_digits=10, verbose_name='Баланс'),
        ),
    ]
