# Generated by Django 5.2.1 on 2025-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='opponent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
